<?php
	$pageTitle = "Security | Rejoiner";
	$metaDescription = "Rejoiner's security policy.";
	include("header.php");
?>

<section id="securityPage">
	<div id="security-header">
		<h1>Our Security Story</h1>
		<p>Rejoiner is committed to providing a transparent security policy.</p>
	</div>
	<div class="security-goals">
		<p class="intro-note"><b>This policy is designed to cover the most frequently asked security questions in concise format</b>. Secondly, this policy can help you determine whether Rejoiner meets your organization’s security requirements.<b>The goal of our policy is to protect all individuals using our platform</b>, including subscribers and end customers, from data theft and other security threats that may undermine their right to privacy.</p>
		<h3>Our Security Planning and Response Team</h3>
		<p>Since we are small company, the responsibilities of maintaining our security requirements are shared by all members of our team. Biannually, our team meets to do a security risk assessment on our platform and determine areas where we need to proactively secure our application. Minutes of these meetings are accessible internally. Any concerns or information you would like to pass on to our security team, please use the contact form <a style="text-transform:underline;" href="/contact" target="_blank">here</a>.</p>
		<h3>Platform and Infrastructure Hosting</h3>
		<p>Our cart abandonment platform is hosted at third party cloud provider known as Softlayer. Softlayer is responsible for all necessary infrastructure related to our private cloud, but is not responsible for our local private network or our system configuration. Physical access is securely restricted to Softlayer’s data center and has many third party certifications, including PCI and ISO 27001 compliance. For more information about Softlayer and the security of their platform, please access their security page <a style="text-transform:underline;" href="http://www.softlayer.com/compliance" target="_blank">here</a>.</p>
		<h3>Data Collection, Retention, and Usage</h3>
		<p>We collect and store data from two entities, subscribers, i.e purchasers of Rejoiner, and end-users, customers shopping on your website. Subscribers of the Rejoiner platform will have access to our metrics and configuration dashboard. This dashboard stores the following data:</p>
			<ul>
				<li>Email</li>
				<li>Password (salted hash)</li>
				<li>Email templates</li>
				<li>Images and logos</li>
			</ul>
		<p>Our API endpoint collects the following information from end users via browser-side Javascript:</p>
			<ul>
				<li>Transaction value total</li>
				<li>Cart items</li>
				<li>Calculated customer age</li>
				<li>Email</li>
				<li>First name</li>
				<li>Plan name</li>
				<li>Plan ID</li>
				<li>Cart Value</li>
				<li>Plan page URL</li>
				<li>Customer conversion (true or false)</li>
			</ul>
		<p>Data collected via our dashboard and API endpoint is stored in perpetuity on encrypted hard drives.  This includes backups of our database. We retain data even when a subscriber cancels their account and unsubscribes from our service. All data, whether generated by the subscriber or the end user, is considered to be confidential, private, and proprietary. We do not share our data with third party services or anyone outside of the Rejoiner team. Internally, we use data for analytics purposes and improving the quality of our platform.</p>
		<h3>Payment Processing</h3>
		<p>Rejoiner does not store any payment processing information. All payment processing is handled by a third party entity Stripe. Stripe supports all industry standards around payment processing, including PCI. For information about security standards at Stripe, please click <a style="text-transform:underline;" href="https://www.google.com/url?q=https%3A%2F%2Fstripe.com%2Fhelp%2Fsecurity&sa=D&sntz=1&usg=AFQjCNHnY_xIz1nkHfaUr863G7_4jLBB_w" target="_blank">here</a>. </p>
		<h3>Server Administration</h3>
		<p>We are passionate about Debian and our servers all run the latest version of Debian. Security updates are applied when available by the Debian security team. SSL vulnerabilities are patched immediately when announced via CVE.  Various security channels are monitored for any vulnerability that may affect our users. Access to our servers is restricted by firewall and SSH certificates. Updates and system configuration is managed by Puppet, a very popular configuration tool.</p>
		<h3>Access Control to Internal Systems</h3>
		<p>All engineers, administrators, and third party contractors have unique credentials to access our systems. This includes login credentials to Rejoiner servers, network devices, third party applications, and the platform itself. Upon leaving the company, these accounts are removed, blocking any further access to the above systems.</p>
		<h3>External and internal networking</h3>
		<p>All of our public facing endpoints require customers to use SSL/TLS encryption. This includes access to our dashboard and API. Communication between servers and internal applications are channelled via private subnets, inaccessible to anyone except administrators. Third party web services and APIs leveraged by the Rejoiner platform communicate through SSL and TLS channels. We do not use or support any HTTP web services under any circumstances. In addition, our external and internal network is monitored via an IDS/IPS system which logs and blocks suspicious network activity. We monitor these reports and logs to ensure that our network is not compromised.</p>
		<h3>Security alerts and notifications</h3>
		<p>In the event of a security breach where we believe your information may have been compromised, we will notify you personally via email with an explanation of the breach along with our strategy for mitigating the threat. All security notifications including important information about recent system updates, SSL vulnerability patching, or general consumable security information will be broadcasted by our dashboard messaging system.</p>
	</div><!-- end security goals -->
</section><!-- end security page -->



<?php include("footer.php"); ?>