<?php
	$pageTitle = "Terms & Conditions | Rejoiner";
	$metaDescription = "Terms and conditions of usage of Rejoiner.";
	include("header.php");
?>

<section style="max-width: 950px; margin: 70px auto 100px auto;" class="terms">
            <h1>Terms of Service</h1>

            <p>These Terms of Service (<strong>“Terms of Service”</strong>), together with the Rejoiner Inc . Privacy Policy available at <a href="http://rejoiner.com/privacy">http://rejoiner.com/privacy</a>  (the <strong>“Privacy Policy”</strong>) and any on-line or written order form for the purchase of the Services (as herein defined) provided hereunder (each, a “Service Order”) , constitute a binding agreement between Rejoiner Inc. (<strong>“Rejoiner”</strong>) and you or the legal entity you represent (<strong>“you”</strong> or the <strong>“User”</strong>). </p> 

<p> desire to use Rejoiner’s on-line consumer tracking platform and related marketing services (the “Services”) and Rejoiner’s user instructions and other documentation relating to the Services which Rejoiner may provide from time to time (the <strong>“Documentation”</strong>).  Rejoiner will permit you to use the Services and the Documentation subject to the terms and conditions of these Terms of Service.  By using the Services you agree to all of the terms and conditions of these Terms of Service, including the limitations on liability set forth herein.  IF YOU DO NOT AGREE WITH ALL OF THE TERMS AND CONDITIONS OF THESE TERMS OF SERVICE, YOU ARE NOT PERMITTED TO USE THE SERVICES. </p>

<dl>
<dt><h5><strong>1.  SERVICES</strong></h5></dt>
<dd><p><u><strong>1.1.    Agreement to Provide Services.</u></strong>  Subject to the terms and conditions of these Terms of Service, during the term of these Terms of Service, Rejoiner will provide to User access to the Services purchased through and described on the Rejoiner website (the “Rejoiner Site”) in accordance with the applicable Service Order(s).  User understands and agrees that by using the on-line registration process and consenting to the terms of these Terms of Service, User has made a binding selection of the type of Services to be provided and all associated specifications, prices, policies and documentation related to the delivery of the Services.</p></dd>
<dd><p><u><strong>1.2.    Service Orders.</u></strong>  Each Service Order is hereby incorporated into these Terms of Service by this reference and is subject to the terms and conditions of these Terms of Service; provided, however, that in the event of conflict between the terms contained in any Service Order, the terms contained in these Terms of Service shall control.  In the event of any conflict between the terms of these Terms of Service or a Service Order and any Customer-issued order form or purchase order, the terms of these Terms of Service and the applicable Service Order shall control.</p></dd>

<dt><h5><strong>2.  MODIFICATIONS TO THESE TERMS OF SERVICE.</strong></h5></dt>  
<dd><p>User agrees that Rejoiner may modify these Terms of Service or any policy or other terms referenced in these Terms of Service including but not limited to the Privacy Policy (collectively, "Additional Policies") at any time by posting a revised version of the Terms of Service and the Additional Policies at the websites listed herein.  Unless otherwise set forth in these Terms of Service, the revised terms shall be effective (a) fifteen (15) days after posting and/or notifying Users of the changes; or (b) upon User’s acceptance if Rejoiner provides a mechanism for your immediate acceptance of the revised terms, such as a click-through confirmation or acceptance button.  By continuing to use or receive the Services after the effective date of any revisions to these Terms of Service or any Additional Policies, User agrees to be bound by the revised Terms of Service or any revised Additional Policies.  It is User’s responsibility to check the websites listed herein regularly for changes to these Terms of Service or the Additional Policies, as applicable.  If User disagrees with any modifications to these Terms of Service, User’s sole and exclusive remedy shall be to terminate the receipt of Services in accordance with Section 11 herein. </dd></p>
</dl>
<dl>
<dt><h5><strong>3.  LICENSE.</strong></h5></dt>
<dd><p><u><strong>3.1.    Grant.</u></strong>  Subject to the terms and conditions of these Terms of Service, Rejoiner grants to User a non-exclusive, non-transferable license during the Term (as defined in Section 11), without the right to sublicense, to, during the Term, (i) use the software and other technology supplied by Rejoiner to enable User to receive or access the Services (the “Rejoiner Platform”) solely for the purposes of accessing and using the Services; and (ii) use the Documentation in connection with the User’s use thereof.  Except for the limited licenses granted hereunder, Rejoiner reserves all rights not expressly granted and no such additional rights may be implied. </p></dd>
<dd><p><u><strong>3.2.    Ownership.</u></strong>  You acknowledge that (i) all right, title and interest in and to the Services, including the Rejoiner Platform and Documentation therein, and all patents, copyrights, trade secrets, trademarks and other proprietary rights embodied therein or associated therewith, are and shall remain with Rejoiner or its third party licensors; (ii) no right or interest in the Services or the Rejoiner Platform is conveyed other than the limited licenses granted herein; (iii) the Services and the Rejoiner Platform are protected by copyright and other intellectual property laws; and (iv) Rejoiner asserts that the Services and the Rejoiner Platform embody valuable confidential and secret information of Rejoiner or its licensors, the development of which required the expenditure of considerable time and money. </p></dd>
<dd><p><u><strong>3.3.    No Modification. </u></strong> You agree that you shall not (i) modify or alter the Rejoiner Platform; (ii) create derivative works of the Rejoiner Platform; (iii) decompile, disassemble, decode or reverse engineer the Rejoiner Platform, translate the Rejoiner Platform or otherwise attempt to learn the source code, structure, algorithms or internal ideas underlying the Rejoiner Platform or reduce the Rejoiner Platform by any other means to a human‑perceivable form; or (iv) bypass, delete or disable any copy protection mechanisms or any security mechanisms.</p></dd>
<dd><p><u><strong>3.4.    Certain Other Obligations.</u></strong>  You agree that you (i) shall not sell, transfer, lend, provide or otherwise make available, or disclose to third parties, the Services or any components thereof; (ii) shall not obscure, alter or remove any notice of any copyright, trademark, trade name, service mark, logo, or other intellectual property or proprietary right designation appearing on or contained within the Services, the Rejoiner Platform, the Documentation or on any other Rejoiner materials; and (iii) shall take all reasonable precautions to prevent unauthorized or improper use of the Services. </p></dd>
<dd><p><u><strong>3.5.    Non-Assertion. </u></strong>  During and after the term of these Terms of Service, User will not assert, nor will User authorize, assist, or encourage any third party to assert, against Rejoiner or any of its customers, end users, vendors, business partners (including third party sellers on websites operated by or on behalf of us), licensors, sublicenses or transferees, any patent infringement or other intellectual property infringement claim with respect to the Rejoiner Platform or the Services.</p></dd>
<dd><p><u><strong>3.6.    Feedback and Comments.</u></strong>   In the event User elects, in connection with any of the Services, to communicate to Rejoiner suggestions for improvements to the Services (“Feedback”), Rejoiner shall be entitled to use the Feedback without restriction, even if User has designated the Feedback as confidential.  User hereby grants to Rejoiner a royalty-free, sublicensable, transferable, perpetual, irrevocable license in and to the Feedback to use in any manner related to the operation of its business.  In addition, Rejoiner hereby disclaims any and all liability for any comments, drawings, depictions, audio clips or other content made available on the Rejoiner Site by users of the Rejoiner Site generally (“Comments”). Further Rejoiner (i) shall have a royalty-free, sublicensable, transferable, perpetual, irrevocable license in and to such Comments to use in any manner related to the operation of its business, and (ii) reserves the right to remove any such Content from the Rejoiner Site immediately in its sole discretion. </p></dd>
<dd><p><u><strong>3.7.    Additional Restrictions Applicable to Demo Periods.</u></strong>    From time to time, Rejoiner may agree to provide User with the Services for evaluation, trial or demonstration at no-cost or a special promotional cost (“Demo Agreement”).  If you have a Demo Agreement, your right to use the Services shall terminate on the expiration date communicated to you by Rejoiner.  By accepting Rejoiner Services on such a basis, User accepts the Services “as is” and waives all express and implied warranties and conditions otherwise provided hereunder during the Demo Agreement period.  Either party upon written notice to the other may cancel the Demo Agreement with immediate effect.  Upon termination or expiration of the Demo Agreement period, User shall either convert to a paid contract covering the Services or immediately terminate use of the Services.</p></dd>
</dl>
<dl>
<dt><h5><strong>4.  FEES AND BILLING</strong></h5></dt>
<dd><p><u><strong>4.1.    Service Fees.</u></strong>   In consideration for the provision of Services to User, User will pay to Rejoiner all Services fees ("Fees") due according to the Service Order.  Charges are exclusive of all applicable taxes, which may be billed to User in addition to the Fees. Rejoiner will provide User thirty (30) days advance notice for any increase in fees or addition of new fees for any existing Services.  Such notice and its effective date will be posted on the Rejoiner Site.  User agrees that it is responsible for checking the Rejoiner Site regularly to confirm whether there are any new fees and their effective date. </p></dd>
<dd><p><u><strong>4.2.    Billing, Invoicing and Payment Terms.</u></strong>  Rejoiner will charge User’s credit card provided in the Service Order the Fees for the Services rendered in each billing period on or after the first day of such billing period.  All billing disputes must be emailed to <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="2048454c506052454a4f494e45520e434f4d">[email&nbsp;protected]</a><script cf-hash='f9e31' type="text/javascript">
/* <![CDATA[ */!function(){try{var t="currentScript"in document?document.currentScript:function(){for(var t=document.getElementsByTagName("script"),e=t.length;e--;)if(t[e].getAttribute("cf-hash"))return t[e]}();if(t&&t.previousSibling){var e,r,n,i,c=t.previousSibling,a=c.getAttribute("data-cfemail");if(a){for(e="",r=parseInt(a.substr(0,2),16),n=2;a.length-n;n+=2)i=parseInt(a.substr(n,2),16)^r,e+=String.fromCharCode(i);e=document.createTextNode(e),c.parentNode.replaceChild(e,c)}}}catch(u){}}();/* ]]> */</script> within fifteen (15) days of delivery of the billing statement, and disputes not made within that time are waived by User.  Late payments hereunder will accrue interest at a rate of one and one-half percent (1 ½ %) per month, or the highest rate allowed by applicable law, whichever is lower.  Rejoiner reserves the right to have User complete a credit application to determine User’s creditworthiness as a condition of receiving further Services.  If Rejoiner must initiate a collections process to recover Fees due and payable hereunder, then User shall pay all costs associated with such collections efforts.  In the event Rejoiner delivers to User an invoice for any Fees or interest payments owed hereunder, such invoiced amounts shall be due within fifteen (15) days of the date of such invoice.  </p></dd>
</dl>
<dl>
<dt><h5><strong>5.  USE OF THE SERVICE.</strong></h5></dt>
<dd><p><u><strong>5.1.    Communications. </u></strong>  User is responsible for obtaining and maintaining all of the appliances, hardware, software and services that you may need to access and use the Services.  Without limiting the foregoing, you must obtain and maintain, and pay all charges, taxes and other costs and fees related to, Internet access, telephone, computer, and other equipment, and any communications or other charges incurred by you to access and use the Services. </p></dd>
<dd><p><u><strong>5.2.    Passwords. </u></strong>  You are responsible for protecting and safeguarding any keys, certificates, passwords, access codes, user IDs or other credentials and login information (collectively, “Passwords”) that have been provided to you or that are generated in connection with your use of the Services.  You will not disclose or make available any Passwords other than to your authorized employees and shall use all commercially reasonable efforts to prevent unauthorized access to, or use of, the Passwords or the Services.  You are fully responsible for all activities that occur in connection with your Passwords.  Without limiting the foregoing, you are responsible for all charges applicable to data and information transmitted to and stored under your account on the Services. </p></dd>
<dd><p><u><strong>5.3.    Downtime. </u></strong> You acknowledge that your access to and use of the Services may be suspended for the duration of any scheduled or unscheduled downtime or unavailability of any portion or all of the Services for any reason, including as a result of power outages, system failures or other interruptions, or any other acts, omissions or failures on the part of Rejoiner.  </p></dd>
<dd><p><u><strong>5.4.    Suspension, Limitation or Termination.</u></strong>   Rejoiner shall be entitled, without liability to you, to immediately suspend, terminate or limit your access to the Services at any time in the event (i) that Rejoiner determines that the Services is being used in violation of applicable federal, state or local law or ordinance, these Terms of Service, or any agreement applicable to the Services; (ii) that Rejoiner determines that the Services are being used in an unauthorized or fraudulent manner; (iii) that Rejoiner determines that the use of the Services adversely affects Rejoiner’s equipment or service to others; (iv) Rejoiner is prohibited by an order of a court or other governmental agency from providing the Services; (v) of a denial of service attack or any other event which Rejoiner determines, in its sole discretion, may create a risk to the Services or to any other customers if the Services were not suspended; or (vi) of a security incident or other disaster that impacts the Services or the security of User Data  and Customer Data.  In addition, Rejoiner shall have the right to immediately deny or suspend access to the Rejoiner Platform or Services in the event Rejoiner is not paid any amount due in connection with the Services or you breach these Terms of Service.  Without limiting the generality of Section 5, Rejoiner shall have no liability for any damages, liabilities or losses as a result of any suspension, limitation or termination of your right to use the Services in accordance with these Terms of Service.</p></dd>
<dd><p><u><strong>5.5.    Prohibited Activities.  </u></strong> You may not use the Services (i) in violation of these Terms of Service, including usage that exceeds storage volume limits or other parameters and restrictions described on the applicable Service Order or on the Rejoiner Site; (ii) to infringe on, violate, dilute or misappropriate the intellectual property rights of any third party or any rights of publicity or privacy; (iii) to violate any law, statute, ordinance or regulation (including but not limited to the laws and regulations governing export/import control (including the Export Administration Regulations, the International Traffic in Arms Regulations, and country-specific economic sanctions programs implemented by the Office of Foreign Assets Control), unfair competition, anti-discrimination and/or false advertising); (iv) to store defamatory, trade libelous, unlawfully threatening, or unlawfully harassing data; (v) to store obscene, pornographic or indecent data in violation of applicable law; or (vi) to introduce or propagate any unauthorized data, malware, viruses, worms, Trojan horses, spyware, worms, other malicious or harmful code.  You may not use the Rejoiner Platform or Services in any application that may involve risks of death, personal injury, property damage or environmental damage.  You may not interfere with or attempt to interfere with or disrupt the integrity, security, functionality or proper working of the Services or the Rejoiner Platform.  You may not attempt to discover or use any license keys, access codes or similar information provided from time to time to Rejoiner.  You may not attempt to discover, access, read, alter, destroy, or damage any programs, data or other information stored on or in connection with the Rejoiner Platform or Services by any other party.  You may access the Services only through the interfaces and protocols provided or authorized by Rejoiner.  You may not access the Rejoiner Platform or Services through unauthorized means, such as unlicensed software clients.  You may not compile or use the Rejoiner provided materials or any other information obtained through the Services or the Rejoiner Platform for the purpose of direct marketing, spamming, unsolicited contacting of sellers or customers, or other impermissible advertising, marketing or other activities, including, without limitation, any activities that violate anti-spamming laws and regulations.</p></dd>
<dd><p><u><strong>5.6.    Changes to the Services. </u></strong> Rejoiner has the right to change, modify, update, add to, discontinue or retire the Services and any aspect or feature thereof, including but not limited to, hours of availability, equipment needed for access or use, and the type of files that can be stored.  Rejoiner will provide notice of material changes to the Rejoiner Platform or Services by posting them at <a href="http://blog.rejoiner.com">http://blog.rejoiner.com</a>.  It is your responsibility to check the Rejoiner Site periodically to inform yourself of any changes.</p></dd>
</dl>
<dl>
<dt><h5><strong>6.  DATA.</strong></h5></dt>
<dd><p><u><strong>6.1.    Data. </u></strong>  As used herein, the term “Data” shall refer collectively to both User Data (as defined below) and Customer Data (as defined below). </p></dd>
<dd><p><u><strong>6.2.    User Data. </u></strong>  You warrant that you are the owner of or legal custodian of all programs, data, information and other content you transmit via the Rejoiner Platform and hosted through the Services (the “User Data”) and have the full authority to transmit and store the User Data through the Services.  You hereby authorize the storage of such User Data by Rejoiner through the Services that you elect to transmit via the Rejoiner Platform.  You acknowledge that you bear sole responsibility for adequate security, protection and backup of your User Data on your equipment.  You understand that the Services may store and backup files that are no longer usable due to corruption from viruses, software malfunctions and other causes, which might result in you restoring files that are no longer usable.  Without limiting the generality of Section 5, Rejoiner will have no liability to you for any unauthorized access to, or use, alteration, corruption, deletion, destruction or loss of any of your User Data. </p></dd>
<dd><p><u><strong>6.3.    Customer Data. </u></strong>  In connection with Rejoiner’s performance of the Services, you authorize Rejoiner to collect online data from your website customers and users via the Rejoiner Platform (the “Customer Data”).  Further, you acknowledge that such Customer Data may constitute Personal Data (as defined below).  Rejoiner will not use such Customer Data for any purpose other than to provide the Services to User or as otherwise directed by User.  If the Services include marketing services, you authorize Rejoiner to use such Customer Data (including, as applicable, User’s customers’ e-mail addresses) to perform such Services.   In addition to the foregoing, you hereby grant to Rejoiner a non-exclusive, perpetual, irrevocable, fully transferable and sublicensable license to use any Customer Data collected by Rejoiner on an aggregated basis for any purpose whatsoever, provided that such license shall not include a right to disclose to any third party any Personal Data.</p></dd>
<dd><p><u><strong>6.4.    Personal Data. </u></strong>   As used herein, the term “Personal Data” means any Data (whether Customer Data or User Data) or personal information that is identifiable to specific individuals.  You acknowledge that the Services may be used to process information that may be regulated by privacy or data protection laws.  You hereby instruct Rejoiner to take such steps in the processing of Personal Data as are reasonably necessary to the performance of Rejoiner’s obligations under these Terms of Service, and agree that such instructions constitute your full and complete instructions as to the means by which Personal Data shall be processed by Rejoiner. To the extent that any privacy or data protection laws impose an obligation upon Rejoiner to comply with an individual’s request for access to or correction of their Personal Data, you agree that you shall satisfy such obligations.  Rejoiner agrees that it shall forward any such individual requests that it receives to you and shall reasonably assist you, at your request and expense, to satisfy such obligations.  You agree that it may be necessary for Rejoiner to access your data to respond to your request for assistance with any technical problems and/or queries, and all such access will be logged by the Services.  You shall hold Rejoiner, its subcontractors, suppliers and licensors harmless from any and all data protection claims relating to such access.  Rejoiner agrees that it shall: (i) not use Personal Data (whether User Data or Customer Data) except for the purposes of delivering the Services contemplated by these Terms of Service and in accordance with the terms of the Privacy Policy; (ii) upon termination of these Terms of Service, remove Personal Data in accordance with your written instructions; (iii) implement security measures reasonably designed to safeguard Personal Data against unauthorized access, loss, destruction, damage or disclosure; and (iv) provide reasonable support to you in complying with any legally mandated request or demand made by any court or governmental authority responsible for enforcing privacy or data protection laws.  Rejoiner may transfer Personal Data to its successor or acquirer in a merger, acquisition or other consolidation, including without limitation the sale of all or substantially all of Rejoiner’s stock or assets or business to which these Terms of Service apply.</p></dd>
</dl>
<dl>
<dt><h5><strong>7.  WARRANTIES, REPRESENTATIONS, AGREEMENTS.</strong></h5></dt>
<dd><p><u><strong>7.1.    Authority. </u></strong>  Each party hereto represents and warrants that (i) it has the full corporate right, power and authority to enter into these Terms of Service, (ii) the execution of these Terms of Service by and the performance of its obligations and duties hereunder do not and will not violate any agreement to which it is a party or by which it is bound, and (iii) when executed and delivered, these Terms of Service will constitute the legal, valid and binding obligation of such party, in accordance with its terms.</p></dd>
<dd><p><u><strong>7.2.    Compliance with Law. </u></strong>  In connection with the subject matter of these Terms of Service, each party agrees to comply with all applicable United States Federal and State laws and regulations. </p></dd>
<dd><p><u><strong>7.3.    Applications and User Data.</u></strong>   User represents and warrants: (i) that User is solely responsible for its User Data, including without limitation, the security of such User Data; (ii) that User has the necessary rights and licenses, consents, permissions, waivers and releases to use the User Data; (iii) that your User Data (a) does not violate, misappropriate or infringe any rights of Rejoiner or any third party, (b) does not constitute defamation, invasion of privacy or publicity, or otherwise violate any rights of any third party, and (c) is not designed for use in any illegal activity or does not promote illegal activities, including, without limitation, in a manner that might be illegal or harmful to any person or entity; or (iv) that your User Data does not distribute, share, or facilitate the distribution of unauthorized data, malware, viruses, Trojan horses, spyware, worms, or other malicious or harmful code. </p></dd>
<dd><p><u><strong>7.4.    Customer Data. </u></strong>   User represents and warrants that: (i) User has implemented a website privacy policy, terms of service or similar website policy governing User’s use and protection of its Customer Data that permits Rejoiner to access User’s Customer Data and to perform the Services with such Customer Data; and (ii) Rejoiner’s collection and use of Customer Data in connection with the performance of the Services  does not violate any such User policies.  Rejoiner shall have no liability whatsoever to User, User’s website users or customers or any third party for any failure by User to obtain the appropriate authorizations or rights from its users or customers to provide such Customer Data to Rejoiner and for the use of such Customer Data in connection with the provision and receipt of the Services hereunder.</p></dd>
<dd><p><u><strong>7.5.    Authorization and Account Information. </u></strong>  User represents and warrants that: (i) the information User provides in connection with User’s registration for the Services is accurate and complete; (ii) if User is registering for the Services as an individual, that User is at least 18 years of age and has the legal capacity to enter into these Terms of Service; and (iii) if registering for the Services as an entity or organization, (a) User is duly authorized to do business in the country or countries where it operates, (b) the individual accepting these Terms of Service and completing the registration for the Services meets the requirements of subsection (ii) above and is an authorized representative of User, and (c) User’s employees, officers, representatives and other agents accessing the Services are duly authorized to access the Services and to legally bind User to these Terms of Service and all transactions conducted under User’s account. </p></dd>
</dl>
<dl>
<dt><h5><strong>8.  LIMITED WARRANTY.</strong></h5></dt>
<dd><p><u><strong>8.1.    Rejoiner Platform and Services. </u></strong>  Rejoiner warrants solely to you that the Rejoiner Platform and the Services, when used in accordance with the terms of these Terms of Service, will function substantially in accordance with the Documentation.  Rejoiner’s sole obligation and your exclusive remedy hereunder with respect to any failure to so function shall be to use reasonable efforts to correct any such failure.  Rejoiner shall have no obligation for any failure resulting from (i) operating system modifications, changes or updates applied by the user; (ii) the use or combination of the Rejoiner Platform or the Services with any other software or hardware not supported by Rejoiner; (iii) causes external to the Rejoiner Platform or the Services, such as problems with the hardware, network or other infrastructure with which the Rejoiner Platform and the Services are used; (iv) unauthorized or improper use of the Rejoiner Platform or the Services; or (v) any modification of the Rejoiner Platform or the Services by anyone other than Rejoiner.</p></dd>
<dd><p><u><strong>8.2.    Disclaimer. </u></strong>  EXCEPT AS EXPRESSLY PROVIDED HEREUNDER, THE REJOINER PLATFORM AND THE SERVICES ARE PROVIDED TO USER “AS IS,” WITHOUT WARRANTY OF ANY KIND.  REJOINER HEREBY DISCLAIMS ALL OTHER WARRANTIES WITH RESPECT TO THESE TERMS OF SERVICE, THE REJOINER PLATFORM OR THE SERVICES, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE OR NON-INFRINGEMENT.  WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, REJOINER DOES NOT WARRANT THAT THE REJOINER PLATFORM OR THE SERVICES WILL MEET YOUR REQUIREMENTS OR OPERATE WITHOUT INTERRUPTION OR DOWNTIME OR BE ERROR FREE. </p></dd>
</dl>
<dl>
<dt><h5><strong>9.  LIMITATION OF LIABILITY.</strong></h5></dt>
<dd><p><u><strong>9.1.</u></strong>      TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL REJOINER, NOR ANY OF ITS AFFILIATES, SUBCONTRACTORS, LICENSORS, SUPPLIERS OR RESELLERS, BE LIABLE TO USER OR ANY OTHER THIRD PARTY FOR LOST REVENUES, LOST PROFITS OR OTHER SPECIAL, INCIDENTAL, INDIRECT, PUNITIVE, CONSEQUENTIAL, RELIANCE OR EXEMPLARY DAMAGES ARISING FROM USER’S OR ANY OTHER THIRD PARTY’S USE OF OR INABILITY TO USE THE SERVICES INCLUDING, BUT NOT LIMITED TO, LOSS OF TECHNOLOGY, LOSS OF DATA OR INTERRUPTION OR LOSS OF USE DAMAGES WHETHER OR NOT REJOINER HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE OR LOSS.  THE MAXIMUM AGGREGATE LIABILITY OF REJOINER, ITS LICENSORS AND RESELLERS ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OF SERVICE, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE, STRICT LIABILITY OR OTHERWISE), SHALL NOT EXCEED THE ACTUAL FEES PAID BY YOU FOR THE SERVICE FOR THE SIX (6) MONTH PERIOD IMMEDIATELY PRECEDING THE INITIAL EVENT GIVING RISE TO LIABILITY HEREUNDER. </p></dd>
<dd><p><u><strong>9.2. </u></strong>     User may not bring any suit or action against Rejoiner for any reason whatsoever more than one (1) year after the cause of action accrued. </p></dd>
</dl>
<dl>
<dt><h5><strong>10. INDEMNIFICATION.</strong></h5></dt> 
<dd><p>User will indemnify and hold Rejoiner, its investors, officers, directors, affiliates, subsidiaries, licensors, agents and employees (collectively, the “Rejoiner Parties”) harmless against any loss, liability, claim, demand, damages, costs and expenses, including reasonable attorney’s fees, resulting from any claim (including third party claims), suit, action or proceeding against a Rejoiner Party, resulting from or arising out of or in connection with (i) claims of intellectual property infringement based on (A) User’s use or combination of the Rejoiner Platform and the Services with any other software or hardware not supported by Rejoiner, if such infringement would not have occurred but for such use or combination; (B) any modification of the Rejoiner Platform and the Services by User; or (C) the use by User of any version of the Rejoiner Platform and/or Services other than the current version of the Rejoiner Platform and/or Services, if such version was made available by Rejoiner with notice that such version was being provided in order to avoid an alleged or potential infringement; or (ii) any breach by you of any representation, warranty or obligation under these Terms of Service. </p>
</p></dd>
<dl>
<dt><h5><strong>11. TERM AND TERMINATION.</strong></h5></dt>
<dd><p><b>11.1. Term.</b></p><p>Subject to Rejoiner’s receipt of all applicable Fees, and unless otherwise terminated in accordance with this Section 11, these Terms of Service shall commence upon User’s acceptance of these Terms of Service and shall continue in effect for the period specified on the applicable Service Order (the “Term”).  Each Service Order shall continue for the Term specified therein, and will automatically renew for subsequent Terms unless either party notifies the other of its intent not to renew such Term at any time prior to such renewal.</p></dd>
<dd><p><b>11.2. Termination By User.</b></p><p>You shall have the right to terminate these Terms of Service at any time upon written notice to Rejoiner stating your desire to terminate these Terms of Service.</p></dd>
<dd><p><b>11.3. Termination By Rejoiner.</b></p><p>Rejoiner shall have the right to terminate these Terms of Service at any time upon written notice to you in the event that you breach any of your obligations under these Terms of Service. In addition, Rejoiner may terminate these Terms of Service upon written notice to User if User becomes the subject of a petition in bankruptcy or any proceeding relating to insolvency, receivership, or liquidation for the benefit of creditors.</p></dd>
<dd><p><b>11.4. Consequences of Termination.</b></p><p>Upon termination of these Terms of Service for any reason, you shall cease to use the Rejoiner Platform, the Services and Documentation. Upon termination, you shall not in be entitled to any refund of any Fees previously paid to Rejoiner.</p></dd>
<dd><p><b>11.5. Data Preservation, Retrieval or Transfer.</b></p><p>In the event of a temporary suspension of your access to Services, (i) Rejoiner will not take any action to intentionally erase or delete your Data stored on the Services; and (ii) applicable Fees will continue to accrue. In the event of the termination of these Terms of Service you may, upon reasonable notice to Rejoiner, elect to retrieve your Data directly. If these Terms of Service are terminated for any reason other than your breach, Rejoiner will not take any action to intentionally erase or delete your Data stored on the Services for a period of thirty (30) days. If these Terms of Service are terminated on account of your breach of these Terms of Service, Rejoiner will not take any action to intentionally erase or delete your Data stored on the Services for a period of fifteen (15) days. In each case, your post-termination retrieval or transfer of Data will be conditioned on Rejoiner’s receipt of all applicable Fees for the period following termination, payment in full of any other amounts owed, and your compliance with such reasonable terms and conditions as Rejoiner may establish with respect to such retrieval or transfer. In addition, if you utilize the professional services of Rejoiner to assist you in connection with such retrieval or transfer, you will be responsible for Rejoiner’s then current charges for such professional services. In the event that Rejoiner does not receive all such Fees and amounts within the thirty (30) day or fifteen (15) day periods described above, or in the event that you fail to notify Rejoiner of your election with respect to your Data within such period, Rejoiner shall have no obligation to continue to store your Data or permit you to retrieve or transfer the same.</p></dd>
<dd><p><b>11.6. Survival.</b></p><p>The following shall survive the termination of these Terms of Service: (i) all liabilities accrued under these Terms of Service prior to the effective date of termination; and (ii) all provisions of Sections 3.2, 3.6, 4, 6.3 (with respect to the license to Customer Data granted therein), 8.2, 9, 10, 11.4, 11.5 11.6 and 12 of these Terms of Service. Subject to the provisions of Section 9 hereof, the rights provided in this Section 11 shall be in addition to any and all rights and remedies available to a non-defaulting party at law or in equity upon any breach of these Terms of Service by the other party.</p></dd>
</dl>
<dl></dl>
<dt><h5><strong><dt>12. MISCELLANEOUS.</strong></h5></dt>
<dd><p><b>12.1. Marketing.</b></p><p>User agrees that with User permission Rejoiner may refer to User by name and trademark in Rejoiner’s marketing materials and web site. User understands and acknowledges that Rejoiner does not certify nor endorse, and has no obligation to certify or endorse, any of User’s products or content.</p></dd>
<dd><p><b>12.2. Entire Agreement.</b></p><p>These Terms of Service sets forth the complete understanding of the parties with respect to the subject matter hereof and supersedes all prior understandings and communications relating thereto.  No term or condition of any other document provided to Rejoiner which is different from, inconsistent with, or in addition to the terms and conditions set forth herein will be binding upon Rejoiner.</p></dd>
<dd><p><b>12.3. Modification; Waiver.</b></p><p>T Rejoiner shall have the right to amend the terms and conditions of these Terms of Service at any time, effective upon posting of an updated version of these Terms of Service at <a href="http://rejoiner.com/terms">http://rejoiner.com/terms</a>.  Rejoiner shall use reasonable efforts to provide you with notice of changes to these Terms of Service, but you are responsible for regularly checking the Rejoiner Site to inform yourself of such changes.  Continued use of the Services after any such changes are posted shall constitute your consent to such changes.  The waiver by either party of a breach of any provision hereof shall not be construed as a waiver of any succeeding breach of the same or any other provision, nor shall any delay or omission on the part of such party to avail itself of any right, power or privilege that it has or may have hereunder operate as a waiver of any right, power or privilege.</p></dd>
<dd><p><b>12.4. Governing Law.</b></p><p>These Terms of Service shall be governed by and construed in accordance with the laws of the Commonwealth of Massachusetts as if made in and performed entirely within Massachusetts.  The parties expressly reject any application to these Terms of Service of the United Nations Convention on Contracts for the International Sale of Goods.  All disputes, actions, claims or causes of action arising out of this these Terms of Service or the Services shall be subject to the exclusive jurisdiction of the state and federal courts located in Massachusetts, and you hereby consent to the jurisdiction of such courts.</p></dd>
<dd><p><b>12.5. Assignment.</b></p><p>User may not assign its rights or delegate any obligations hereunder without the express prior written consent of Rejoiner.  Any assignment by User without the prior written consent of Rejoiner shall be null and void.  Rejoiner may assign its rights or obligations hereunder without notice or consent; provided, however, that the Services shall continue to operate as specified in these Terms of Service.  These Terms of Service shall inure to the benefit of each party’s permitted successors and assigns.</p></dd>
<dd><p><b>12.6. Force Majeure.</b></p><p>If either party is unable to perform any of its obligations hereunder (other than payment obligations) due to any act of God, fire, casualty, flood, war, strike, shortage or any other cause beyond its reasonable control, and if such party uses reasonable efforts to avoid such occurrence and minimize its duration and gives prompt notice to the other party, then the affected party’s performance shall be excused and the time for its performance shall be extended for the period of delay or inability to perform.  If the force majeure continues for more than thirty (30) calendar days, then either party may terminate these Terms of Service for convenience upon written notice to the other party.</p></dd>
<dd><p><b>12.7. Successors and Assigns.</b></p><p>These Terms of Service is binding upon and inures to the benefit of the parties hereto and their respective successors and assigns.  Either party may assign or otherwise transfer these Terms of Service or its rights and duties hereunder to a successor of all or substantially all of its assets or business that relate to these Terms of Service. </p></dd>
<dd><p><b>12.8. Severability.</b></p><p>In the event that any provision contained herein shall for any reason be held invalid, illegal or unenforceable in any respect by a court of competent jurisdiction, to such extent such provision shall be deemed null and void and severed from these Terms of Service, and the remainder hereof shall remain in full force and effect and enforceable.</p></dd>
<dd><p><b>12.9. Independent Contractor.</b></p><p>Neither party shall be deemed to be an agent of the other party and the relationship of the parties shall be that of independent contractors. Neither party shall have any right or authority to assume any obligations, or to make any representations or warranties, whether express or implied, on behalf of the other party, or to bind the other party in any matter whatsoever.</p></dd>
<dd><p><b>12.10. Notices.</b></p><p>Except as otherwise provided, notices under these Terms of Service shall be delivered by email addressed to the other party at such address as is set forth in the applicable Service Order or such other email address, in the case of Rejoiner, as Rejoiner may provided to you from time to time, or in your case, as you may provide from time to Rejoiner by modifying your user profile via the Rejoiner Platform.  Such notice will be deemed to have been given as of the date it is delivered by electronic mail, personally, by confirmed facsimile or by courier, or five (5) days after it is sent by mail. All communications and notices to be made or given pursuant to these Terms of Service shall be in the English language.</p></dd>
<dd><p><b>12.11. Compliance With Laws.</b></p><p>You agree to comply at all times with all laws, rules and regulations applicable to your use of the Services.</dd>
<dd><p><b>12.12. Headings.</b></p><p>The headings of the sections of these Terms of Service are for convenience of reference only and shall not be considered in construing these Terms of Service. </dd>
<br><br>
<p>If you have any question or concerns about what has been stated in this Terms of Service, please feel free to contact us at <a href="/cdn-cgi/l/email-protection#0a626f667a4a786f606563646f7824696567"><span class="__cf_email__" data-cfemail="ec8489809cac9e8986838582899ec28f8381">[email&nbsp;protected]</span><script cf-hash='f9e31' type="text/javascript">
/* <![CDATA[ */!function(){try{var t="currentScript"in document?document.currentScript:function(){for(var t=document.getElementsByTagName("script"),e=t.length;e--;)if(t[e].getAttribute("cf-hash"))return t[e]}();if(t&&t.previousSibling){var e,r,n,i,c=t.previousSibling,a=c.getAttribute("data-cfemail");if(a){for(e="",r=parseInt(a.substr(0,2),16),n=2;a.length-n;n+=2)i=parseInt(a.substr(n,2),16)^r,e+=String.fromCharCode(i);e=document.createTextNode(e),c.parentNode.replaceChild(e,c)}}}catch(u){}}();/* ]]> */</script></a>.
</p>

<p><strong>Last Updated:  These Terms of Service were last updated February 23, 2012.</strong></p>

</section>
			


<?php include("footer.php"); ?>